language: ruby
install: bundle install --path vendor/bundle
cache:
  directories: vendor/bundle
addons:
  hosts:
    - vvv.dev
    - local.wordpress.dev
    - local.wordpress-trunk.dev
    - src.wordpress-develop.dev
    - build.wordpress-develop.dev

before_script:
    - sudo rm -rf ~/.gnupg
    - sudo mkdir /srv/database && sudo mount --bind `pwd`/database /srv/database
    - sudo mkdir /srv/config && sudo mount --bind `pwd`/config /srv/config
    - sudo mkdir /srv/www && sudo mount --bind `pwd`/www /srv/www
    - sudo bash provision/provision.sh

script: TARGET=localhost bundle exec rake spec
